// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Formicarium$Type } from "./Formicarium";
import { IERC20$Type } from "./IERC20";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Formicarium"]: Formicarium$Type;
    ["IERC20"]: IERC20$Type;
    ["contracts/formicarium.sol:Formicarium"]: Formicarium$Type;
    ["contracts/formicarium.sol:IERC20"]: IERC20$Type;
  }

  interface ContractTypesMap {
    ["Formicarium"]: GetContractReturnType<Formicarium$Type["abi"]>;
    ["IERC20"]: GetContractReturnType<IERC20$Type["abi"]>;
    ["contracts/formicarium.sol:Formicarium"]: GetContractReturnType<Formicarium$Type["abi"]>;
    ["contracts/formicarium.sol:IERC20"]: GetContractReturnType<IERC20$Type["abi"]>;
  }
}
